CREATE TABLE IF NOT EXISTS user ( user_id VARCHAR(10) PRIMARY KEY, username TEXT NOT NULL UNIQUE, channel_id VARCHAR(5), password TEXT NOT NULL, user_type VARCHAR(6) NOT NULL, FOREIGN KEY (channel_id) REFERENCES channel(channel_id) ON UPDATE CASCADE ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS channel ( channel_id VARCHAR(5) PRIMARY KEY, channel_name TEXT NOT NULL, channel_description TEXT, password TEXT NOT NULL, owner_id VARCHAR(10), FOREIGN KEY (owner_id) REFERENCES user (user_id) ON UPDATE CASCADE ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS message ( sender_id VARCHAR(10), channel_id VARCHAR(5), message_id INTEGER PRIMARY KEY AUTOINCREMENT, timestamp DATETIME NOT NULL, content TEXT NOT NULL, FOREIGN KEY (sender_id) REFERENCES user(user_id) ON UPDATE CASCADE ON DELETE CASCADE, FOREIGN KEY (channel_id) REFERENCES channel(channel_id) ON UPDATE CASCADE ON DELETE CASCADE);
